packages:
  - apps/*
  - packages/*

minimumReleaseAge: 120

minimumReleaseAgeExclude:
  - turbo-linux-arm64

onlyBuiltDependencies:
  - '@prisma/engines'
  - '@swc/core'
  - esbuild
  - prisma
  - sharp
